### PR TITLE
Benched truncate function with alternatives

### PR DESCRIPTION
**Pull request by Wicpar**
So this is a comparison benchmark comparing the master implementations to other alternatives.
Oddly enough the unrolled one and the bits should be exactly as fast for 1 byte chars, but they are not...

I anly had my m1 mac to do the benchmarks so it's pretty much arm optimized, i will have access to my main computer back after the weekend

More unit tests testing the limits should be implemented for the bits function, it quite whacky, but really shines on the 3 and 4 byte chars, and is pretty much as fast on the other circumstances (except one byte for a mysterious reason)

### CODE REVIEW

**Comment by Wicpar** [comment]
results on m1

```
truncate_master 1byte   time:   [945.04 ps 946.91 ps 949.02 ps]                                   
                        change: [+0.6458% +0.8589% +1.0777%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

truncate_naive 1byte    time:   [1.2506 ns 1.2513 ns 1.2521 ns]                                  
                        change: [-0.1828% -0.0265% +0.1355%] (p = 0.75 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  5 (5.00%) high mild
  7 (7.00%) high severe

truncate_unrolled 1byte time:   [938.44 ps 939.85 ps 941.78 ps]                                     
                        change: [-0.0954% +0.0629% +0.2029%] (p = 0.45 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  6 (6.00%) high mild
  6 (6.00%) high severe

truncate_bits 1byte     time:   [1.2509 ns 1.2513 ns 1.2519 ns]                                 
                        change: [-0.1243% +0.0193% +0.1700%] (p = 0.79 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  6 (6.00%) high mild
  6 (6.00%) high severe

truncate_master 2byte   time:   [1.5635 ns 1.5641 ns 1.5648 ns]                                   
                        change: [-0.1299% -0.0121% +0.1042%] (p = 0.85 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  4 (4.00%) high mild
  4 (4.00%) high severe

truncate_naive 2byte    time:   [1.5645 ns 1.5676 ns 1.5716 ns]                                  
                        change: [+0.0104% +0.1562% +0.3104%] (p = 0.05 < 0.05)
                        Change within noise threshold.
Found 14 outliers among 100 measurements (14.00%)
  5 (5.00%) high mild
  9 (9.00%) high severe

truncate_unrolled 2byte time:   [1.5638 ns 1.5647 ns 1.5659 ns]                                     
                        change: [-0.3315% -0.1534% +0.0057%] (p = 0.07 > 0.05)
                        No change in performance detected.
Found 14 outliers among 100 measurements (14.00%)
  7 (7.00%) high mild
  7 (7.00%) high severe

truncate_bits 2byte     time:   [1.5635 ns 1.5640 ns 1.5646 ns]                                 
                        change: [-0.1842% -0.0402% +0.0858%] (p = 0.58 > 0.05)
                        No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
  5 (5.00%) high mild
  5 (5.00%) high severe

truncate_master 3byte   time:   [1.5634 ns 1.5650 ns 1.5678 ns]                                   
                        change: [-0.6929% -0.3378% -0.0557%] (p = 0.03 < 0.05)
                        Change within noise threshold.
Found 11 outliers among 100 measurements (11.00%)
  6 (6.00%) high mild
  5 (5.00%) high severe

truncate_naive 3byte    time:   [1.5773 ns 1.5956 ns 1.6216 ns]                                  
                        change: [+1.7286% +4.0285% +6.5118%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 19 outliers among 100 measurements (19.00%)
  2 (2.00%) high mild
  17 (17.00%) high severe

truncate_unrolled 3byte time:   [1.5759 ns 1.5808 ns 1.5871 ns]                                     
                        change: [-0.5446% +0.2646% +0.8873%] (p = 0.51 > 0.05)
                        No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
  5 (5.00%) high mild
  5 (5.00%) high severe

truncate_bits 3byte     time:   [1.5633 ns 1.5638 ns 1.5644 ns]                                 
                        change: [-0.1045% -0.0005% +0.1083%] (p = 0.99 > 0.05)
                        No change in performance detected.
Found 13 outliers among 100 measurements (13.00%)
  5 (5.00%) high mild
  8 (8.00%) high severe

truncate_master 4byte   time:   [3.4486 ns 3.4556 ns 3.4638 ns]                                   
                        change: [-0.8491% -0.5756% -0.3140%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

truncate_naive 4byte    time:   [3.4690 ns 3.4752 ns 3.4820 ns]                                  
                        change: [-6.2146% -3.7840% -1.7042%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe

truncate_unrolled 4byte time:   [1.8778 ns 1.8788 ns 1.8800 ns]                                     
                        change: [-0.6038% -0.3642% -0.1290%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high mild

truncate_bits 4byte     time:   [1.5635 ns 1.5649 ns 1.5673 ns]                                 
                        change: [-3.3757% -2.2619% -1.3866%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
  7 (7.00%) high mild
  4 (4.00%) high severe

```

**Comment by paulocsanz** [comment]
That is nice! It sure becomes significant with more bytes!

**Comment by paulocsanz** [comment]
I use the ffi module to get the assembly, it avoid inlining though.

Btw, I ran the tests with miri and it's complaining about push_str_unchecked, it might sound but in a way that miri can't understand, but maybe we can rewrite to not be ambiguous? I'm trying but I don't really understand what is going on. Maybe your re-write does better?

**Comment by Wicpar** [comment]
Which one is it complaining about? 
This pr should have changed nothing from your original code in push_str_unchecked

**Comment by Wicpar** [comment]
So about the miri thing, i pulled the master and verified my PR didn't touch that, it's there too, so that UB preexisted my changes :/

i'll check with miri before doing a new PR

**Comment by paulocsanz** [comment]
Yes, the UB preexisted your changes. What I meant with it was that since you are changing it, if your changes could make miri work it would be incredible and make it much easier to justify the change.

I want the lib to be safer, it feels hard to review a complete change of the inner workings because it's battle tested. But if those changes can help some tooling garantee that the code is safer, it becomes a no-brainer and the review becomes much easier to do.

**Comment by Wicpar** [comment]
alright, i'll do that

**Comment by Wicpar** [comment]
I've been thinking, it may be wise to merge this one too:
The compiler improves regularly, able to optimize better from time to time, so it would be interesting to keep approaches benched in case that changes and suddenly an approach gets a significant speed boost.
For instance it looks like the copy_from_slice is unable to optimize small copies, it could be interesting to benchmark custom copies too, maybe a "hack" where the slice is transmuted to an array and then set into the struct without copying the data if > than the slice for truncate, and then we set the size to the closest valid char boundary.

**Comment by paulocsanz** [comment]
That makes sense, could you fix the merge conflicts please?

**Comment by paulocsanz** [comment]
No-panic is kind of dangerous in production btw, as it might break unexpectedly with a compiler update. I'm thinking it should be behind a feature flag

**Comment by Wicpar** [comment]
Yes we can do that, there is already a cfg_attr on it anyway:)

**Comment by Wicpar** [comment]
I'll do the changes asap, i'm currently traveling, i'm not sure when i'll have time.

**Comment by paulocsanz** [comment]
What I meant is that the current cfg_attr means people using this in production may observe a compilation failure because they are using a different compiler version than us.

**Comment by paulocsanz** [comment]
I currently have a local branch with the no-panic cargo feature and added the no_panic attribute in every function.

A lot of panics appeared, I'm slowly fixing them but it's requiring unsafe. A lot of it was `copy_within` not having its panic being optimized, so I copied it.

There still are a bunch of panics to solve, but looking at the new unsafe usages I agree that using replace_range everywhere might be the way to go. I haven't done that, I might next week as I won't be working, but I can't promise it. If you want I can make a PR for you to see what I'm talking about.

**Comment by Wicpar** [comment]
no need for a pr if you have it in a branch, i can check it out.
i did more optimizing and am coming to the hard conclusion that the optimizer is not able to generalize small string to always use registers, i'll see if creating a NumString is faster, based on Numtrait integers so it can be u32 to u128 and using bit operations for the string operations.

**Comment by paulocsanz** [comment]
I'm happy avoiding those trait hacks like we had before and using stable const generics even if it hurts performance.

I will push that branch later, we should be careful to not step on each others toes, as changing multiple stuff simultaneously will make it hard to merge things. I had to change a bunch of functions and even then a bunch of others can still panic.

**Comment by paulocsanz** [comment]
I decided that I won't merge this, it's useful but not really needed for the package, the PR will still be here albeit closed, so we can use it as a reference in the future.

**Comment by Wicpar** [comment]
sure thing, the results were not great anyway

**Pull request closed without merging**
